import { Filter, ScanLine, Sparkles, Volume2 } from "lucide-react";
import { Button, SearchField, Section } from "../ui";

type PatientFilterBarProps = { query: string; status: string; gender: string; startDate: string; endDate: string; onQueryChange: (value: string) => void; onStatusChange: (value: string) => void; onGenderChange: (value: string) => void; onStartDateChange: (value: string) => void; onEndDateChange: (value: string) => void; onReset: () => void };
const statusOptions = ["All", "Active", "Under Observation", "Discharged", "Critical", "Inactive"];
const genderOptions = ["All", "Female", "Male", "Other"];

export default function PatientFilterBar({ endDate, gender, onEndDateChange, onGenderChange, onQueryChange, onReset, onStartDateChange, onStatusChange, query, startDate, status }: PatientFilterBarProps) {
  return <Section title="Find and filter patients" description="Search identity, clinical history, care team, department, blood group, and registration date." action={<Filter className="h-5 w-5 text-cyan-700" aria-hidden="true" />}><div className="grid gap-4 xl:grid-cols-[minmax(250px,1.4fr)_repeat(4,minmax(130px,0.6fr))]"><SearchField value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Name, ID, phone, doctor, diagnosis…" label="Search patients" /><label className="text-sm font-medium text-slate-700 dark:text-slate-200">Status<select value={status} onChange={(event) => onStatusChange(event.target.value)} className="mt-2 min-h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950">{statusOptions.map((option) => <option key={option}>{option}</option>)}</select></label><label className="text-sm font-medium text-slate-700 dark:text-slate-200">Gender<select value={gender} onChange={(event) => onGenderChange(event.target.value)} className="mt-2 min-h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950">{genderOptions.map((option) => <option key={option}>{option}</option>)}</select></label><label className="text-sm font-medium text-slate-700 dark:text-slate-200">Registered from<input type="date" value={startDate} onChange={(event) => onStartDateChange(event.target.value)} className="mt-2 min-h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950" /></label><label className="text-sm font-medium text-slate-700 dark:text-slate-200">Registered to<input type="date" value={endDate} onChange={(event) => onEndDateChange(event.target.value)} className="mt-2 min-h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950" /></label></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500 dark:text-slate-400">Barcode, QR, voice, and AI-assisted search are ready for future service integration.</p><div className="flex flex-wrap gap-2"><Button variant="ghost" disabled title="Available with device integration"><ScanLine className="h-4 w-4" />Barcode</Button><Button variant="ghost" disabled title="Available with voice search integration"><Volume2 className="h-4 w-4" />Voice</Button><Button variant="ghost" disabled title="Available with AI search integration"><Sparkles className="h-4 w-4" />AI search</Button><Button variant="secondary" onClick={onReset}>Reset filters</Button></div></div></Section>;
}
