import { AlertTriangle, CalendarDays, Download, FileText, FlaskConical, HeartPulse, Pill, Printer, ReceiptText, Sparkles, Stethoscope } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { PatientRecord } from "../../stores/patientStore.ts";
import { Avatar, Badge, Button, MetricCard, PageHeader, Section } from "../ui";
import { getPatientPresentation, riskVariant, statusVariant } from "./patientPresentation";

export default function PatientProfileWorkspace({ patient }: { patient: PatientRecord }) {
  const navigate = useNavigate();
  const presentation = getPatientPresentation(patient);
  const documents = ["Patient summary", "Medical record", "Prescription", "Laboratory report", "Billing invoice", "Admission form", "Discharge summary"];
  const timeline = [["Registration", patient.registrationDate, "Patient record created and identity verified."], ["Consultation", "Today", `Care assignment: ${presentation.doctor}.`], ["Laboratory", "Awaiting data", "Laboratory results will be shown after service integration."], ["Pharmacy", "Awaiting data", "Prescription and dispensing data will be shown here."], ["Billing", "Awaiting data", "Billing status will be shown here."]];
  return <div className="space-y-6"><PageHeader eyebrow={`Patient ID: ${patient.id}`} title={patient.fullName} description={`${presentation.department} · ${presentation.doctor}`} actions={<><Button variant="secondary" onClick={() => navigate("/appointments")}><CalendarDays className="h-4 w-4" />Schedule appointment</Button><Button onClick={() => navigate("/patients")}>Back to registry</Button></>} />
    <section className="grid gap-4 lg:grid-cols-[1.4fr_repeat(3,minmax(0,0.7fr))]"><Section className="lg:row-span-1"><div className="flex flex-wrap items-center gap-4"><Avatar name={patient.fullName} size="lg" /><div><p className="text-lg font-semibold text-slate-900 dark:text-slate-100">{patient.fullName}</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{patient.age} years · {patient.gender} · {patient.bloodGroup}</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant={statusVariant(patient.status)}>{patient.status}</Badge><Badge variant={riskVariant(presentation.risk)}>{presentation.risk} risk</Badge><Badge variant="neutral">{presentation.patientType}</Badge></div></div></div></Section><MetricCard label="Care team" value={presentation.doctor} description={presentation.department} icon={<Stethoscope className="h-5 w-5" />} /><MetricCard label="Latest visit" value="Today" description="Clinical timeline ready" icon={<HeartPulse className="h-5 w-5" />} /><MetricCard label="Billing status" value="Pending" description="Awaiting billing service" icon={<ReceiptText className="h-5 w-5" />} /></section>
    <section className="grid gap-6 xl:grid-cols-2"><Section title="Personal and contact information"><dl className="grid gap-4 sm:grid-cols-2">{[["Phone", patient.phone], ["Email", patient.email], ["Address", patient.address], ["Emergency contact", "Not recorded — future integration"], ["Insurance", "Not recorded — future integration"], ["Admission date", patient.registrationDate]].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500 dark:text-slate-400">{label}</dt><dd className="mt-1 text-sm text-slate-800 dark:text-slate-200">{value}</dd></div>)}</dl></Section><Section title="Medical history" description="Clinical record summary"><div className="space-y-3">{patient.medicalHistory.length ? patient.medicalHistory.map((item) => <div key={item} className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700 dark:bg-slate-900 dark:text-slate-200">{item}</div>) : <p className="text-sm text-slate-500">No medical history recorded.</p>}<p className="text-xs text-slate-500 dark:text-slate-400">Allergies, current medications, diagnoses, and clinical notes will appear when connected to clinical services.</p></div></Section></section>
    <section className="grid gap-6 xl:grid-cols-3"><Section title="Laboratory results" action={<FlaskConical className="h-5 w-5 text-cyan-700" />}><p className="text-sm text-slate-600 dark:text-slate-400">No laboratory results are attached to this record.</p><Button variant="ghost" disabled className="mt-4">View lab reports</Button></Section><Section title="Prescriptions" action={<Pill className="h-5 w-5 text-cyan-700" />}><p className="text-sm text-slate-600 dark:text-slate-400">Prescription data will appear after pharmacy integration.</p><Button variant="ghost" disabled className="mt-4">View prescriptions</Button></Section><Section title="AI clinical insights" action={<Sparkles className="h-5 w-5 text-cyan-700" />}><p className="text-sm text-slate-600 dark:text-slate-400">Risk prediction, readmission risk, drug interactions, and follow-up suggestions are reserved for a future AI service.</p><Badge variant="neutral" className="mt-4">No insights generated</Badge></Section></section>
    <section className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><Section title="Visit timeline" description="Chronological patient care events"><ol className="space-y-5 border-l border-slate-200 pl-5 dark:border-slate-700">{timeline.map(([title, date, detail]) => <li key={title} className="relative"><span className="absolute -left-[1.65rem] top-1.5 h-3 w-3 rounded-full bg-cyan-700 ring-4 ring-white dark:ring-slate-950" /><p className="text-sm font-semibold text-slate-900 dark:text-slate-100">{title}</p><p className="text-xs text-slate-500 dark:text-slate-400">{date}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{detail}</p></li>)}</ol></Section><Section title="Document center" description="Professional record outputs become available with document services."><div className="space-y-2">{documents.map((document) => <div key={document} className="flex items-center justify-between gap-3 rounded-lg border border-slate-200 p-3 dark:border-slate-800"><div className="flex items-center gap-2 text-sm font-medium text-slate-800 dark:text-slate-200"><FileText className="h-4 w-4 text-cyan-700" />{document}</div><div className="flex gap-1"><Button variant="ghost" disabled className="min-h-8 px-2" title="Available with document generation"><Download className="h-4 w-4" /><span className="sr-only">Download {document}</span></Button><Button variant="ghost" disabled className="min-h-8 px-2" title="Available with document generation"><Printer className="h-4 w-4" /><span className="sr-only">Print {document}</span></Button></div></div>)}</div><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">Future documents include hospital branding, audit metadata, QR verification, digital signature placeholders, and print page numbering.</p></Section></section>
    <Section title="Priority actions" description="Actions preserve existing workflow routing; unavailable actions await their service integrations."><div className="flex flex-wrap gap-2"><Button onClick={() => navigate("/patients")}>Edit patient</Button><Button variant="secondary" onClick={() => navigate("/appointments")}>Schedule appointment</Button><Button variant="secondary" disabled>Admit patient</Button><Button variant="secondary" disabled>Discharge patient</Button><Button variant="secondary" disabled>Generate invoice</Button><Button variant="secondary" disabled>Download medical record</Button></div><div className="mt-4 flex items-start gap-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-100"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />Admission, discharge, billing, and document actions remain unavailable until their API contracts are integrated.</div></Section>
  </div>;
}
