import { useState } from "react";
import { CheckCircle2, Download, ShieldCheck } from "lucide-react";
import { Badge, Button, EmptyState, LoadingState, PageHeader, Section } from "../../components/ui";
import { ErrorPanel, JsonViewer, ValidationPanel } from "../components/common";
import ExportDialog from "../components/ExportDialog";
import PatientSelect from "../components/PatientSelect";
import { api, ApiError } from "../api/client";
import type { BundleSummary, Consent, FhirJson, ValidationResult } from "../api/types";
import { useApi } from "../hooks/useApi";
import { usePatients } from "../hooks/usePatients";
import { formatDateTime } from "../lib";

export default function Bundles() {
  const patients = usePatients(["custodian"]);
  const current = patients.current;
  const [openId, setOpenId] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [genError, setGenError] = useState<ApiError | null>(null);
  const [showJson, setShowJson] = useState(false);
  const [validation, setValidation] = useState<ValidationResult | null>(null);
  const [valBusy, setValBusy] = useState(false);
  const [valError, setValError] = useState<ApiError | null>(null);
  const [exportOpen, setExportOpen] = useState(false);

  const bundles = useApi(() => api.get<{ bundles: BundleSummary[] }>("/fhir/bundles"), []);
  const shown = (bundles.data?.bundles ?? []).filter((b) => !current || b.patientId === current.id);
  const activeId = openId && shown.some((b) => b.id === openId) ? openId : shown[0]?.id ?? null;
  const detail = useApi(() => api.get<{ summary: BundleSummary; bundle: FhirJson; validation: ValidationResult }>(`/fhir/bundles/${activeId}`), [activeId], Boolean(activeId));
  const consents = useApi(() => api.get<{ consents: Consent[] }>(`/consent?patientId=${current?.id}`), [current?.id], Boolean(current) && exportOpen);

  async function generate() {
    if (!current) return;
    setBusy(true);
    setGenError(null);
    try {
      const r = await api.post<{ summary: BundleSummary }>("/fhir/bundle", { patientId: current.id });
      setOpenId(r.summary.id);
      setValidation(null);
      setShowJson(false);
      bundles.reload();
    } catch (e) {
      setGenError(e as ApiError);
    } finally {
      setBusy(false);
    }
  }

  async function validate() {
    if (!activeId) return;
    setValBusy(true);
    setValError(null);
    try {
      setValidation(await api.post<ValidationResult>("/fhir/validate", { bundleId: activeId }));
    } catch (e) {
      setValError(e as ApiError);
    } finally {
      setValBusy(false);
    }
  }

  const d = detail.data;
  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Part 6 · FHIR" title="FHIR Bundles" description="Assemble a patient's resources into a FHIR collection Bundle, validate it (including that every reference resolves) and export it under consent." />
      {patients.loading && <LoadingState />}
      {patients.error && <ErrorPanel error={patients.error} onRetry={patients.reload} />}
      {!patients.loading && !patients.error && !current && <EmptyState title="No records held by your organisation" description="Bundles can only be generated by the data custodian." />}
      {current && (
        <>
          <Section title="Bundle generator">
            <div className="space-y-4">
              <PatientSelect rows={patients.rows} value={current.id} onChange={(id) => { patients.select(id); setOpenId(null); setValidation(null); }} />
              <Button loading={busy} onClick={() => void generate()}>Generate FHIR Bundle</Button>
              {genError && <ErrorPanel error={genError} />}
            </div>
          </Section>

          <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]">
            <Section title="Bundles" description={`${shown.length} for this patient`}>
              {bundles.loading && <LoadingState />}
              {bundles.error && <ErrorPanel error={bundles.error} onRetry={bundles.reload} />}
              {bundles.data && shown.length === 0 && <EmptyState title="No bundles yet" description="Generate a bundle to see it here." />}
              <ul className="space-y-2">
                {shown.map((b) => (
                  <li key={b.id}>
                    <button type="button" onClick={() => { setOpenId(b.id); setValidation(null); setShowJson(false); }} className={`w-full rounded-lg border p-3 text-left text-sm ${activeId === b.id ? "border-cyan-500 bg-cyan-50/60 dark:border-cyan-700 dark:bg-cyan-950/30" : "border-slate-200 hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-900"}`}>
                      <span className="flex items-center justify-between gap-2"><code className="font-semibold">{b.id}</code><Badge variant={b.validation.status === "VALID" ? "success" : "danger"}>{b.validation.status}</Badge></span>
                      <span className="mt-1 block text-xs text-slate-500">{b.entryCount} entries · {formatDateTime(b.createdAt)}</span>
                    </button>
                  </li>
                ))}
              </ul>
            </Section>

            <Section title="FHIR Bundle" description="FHIR DEMO RESOURCE">
              {!activeId && <EmptyState title="Select a bundle" />}
              {activeId && detail.loading && <LoadingState />}
              {activeId && detail.error && <ErrorPanel error={detail.error} onRetry={detail.reload} />}
              {d && (
                <div className="space-y-5">
                  <dl className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-4">
                    <div><dt className="text-xs text-slate-500">Bundle ID</dt><dd><code>{d.summary.id}</code></dd></div>
                    <div><dt className="text-xs text-slate-500">Bundle type</dt><dd className="font-semibold">{d.summary.type}</dd></div>
                    <div><dt className="text-xs text-slate-500">Entries</dt><dd className="font-semibold">{d.summary.entryCount}</dd></div>
                    <div><dt className="text-xs text-slate-500">Created</dt><dd>{formatDateTime(d.summary.createdAt)}</dd></div>
                    <div><dt className="text-xs text-slate-500">Validation</dt><dd><Badge variant={d.validation.status === "VALID" ? "success" : "danger"}>{d.validation.status}</Badge></dd></div>
                    <div className="col-span-3"><dt className="text-xs text-slate-500">Integrity checksum (SHA-256)</dt><dd className="truncate"><code className="text-xs">{d.summary.checksum}</code></dd></div>
                  </dl>
                  <ul className="grid gap-1.5 text-sm sm:grid-cols-2">
                    {(d.bundle.entry as { resource: { resourceType: string; id: string } }[]).map((e) => (
                      <li key={`${e.resource.resourceType}/${e.resource.id}`} className="flex items-center gap-2">
                        <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" aria-hidden="true" />
                        <span className="font-medium">{e.resource.resourceType}</span>
                        <code className="truncate text-xs text-slate-500">{e.resource.id}</code>
                      </li>
                    ))}
                  </ul>
                  <div className="flex flex-wrap gap-2">
                    <Button variant="secondary" onClick={() => setShowJson((v) => !v)}>{showJson ? "Hide JSON" : "View JSON"}</Button>
                    <Button variant="secondary" loading={valBusy} onClick={() => void validate()}><ShieldCheck className="h-4 w-4" aria-hidden="true" />Validate</Button>
                    <Button onClick={() => setExportOpen(true)}><Download className="h-4 w-4" aria-hidden="true" />Export</Button>
                  </div>
                  {valError && <ErrorPanel error={valError} />}
                  {validation && <ValidationPanel result={validation} />}
                  {showJson && <JsonViewer data={d.bundle} />}
                </div>
              )}
            </Section>
          </div>
          <ExportDialog open={exportOpen} onClose={() => setExportOpen(false)} consents={consents.data?.consents ?? []} />
        </>
      )}
    </div>
  );
}
