import { ReactNode } from "react";
import { FileText, ShieldCheck, Sparkles, TriangleAlert } from "lucide-react";
import Badge from "../../../components/ui/Badge";
import type { Evidence, Finding, ReviewState, Severity } from "../types";
import { URGENCY_LABEL, formatDate, provenanceFrame, reviewLabel } from "../helpers";

// ---- Provenance grammar -------------------------------------------------------------------------
// record      → verified content that was supplied to the system            (solid, neutral)
// rules       → deterministic rule output, reproducible, not AI             (solid, blue tag)
// ai          → generated by an AI model, NOT verified                      (dashed violet frame, violet tag)
export type Provenance = "record" | "rules" | "ai";

export function OriginTag({ origin, detail }: { origin: Provenance; detail?: string }) {
  if (origin === "ai") {
    return <span title={detail ?? "Generated by an AI model. Not verified."} className="inline-flex items-center gap-1 rounded-full bg-violet-100 px-2.5 py-1 text-xs font-semibold text-violet-800 dark:bg-violet-900/50 dark:text-violet-200"><Sparkles className="h-3 w-3" aria-hidden="true" />AI-generated</span>;
  }
  if (origin === "rules") {
    return <span title="Produced by deterministic rules. Reproducible; not AI." className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700 dark:bg-blue-950/50 dark:text-blue-200"><ShieldCheck className="h-3 w-3" aria-hidden="true" />Rule-based</span>;
  }
  return <span title="Taken directly from the supplied clinical record." className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-200"><FileText className="h-3 w-3" aria-hidden="true" />Record</span>;
}

const SEVERITY: Record<Severity, { label: string; variant: "danger" | "warning" | "info" | "neutral"; bar: string }> = {
  high: { label: "High priority", variant: "danger", bar: "border-l-rose-600" },
  moderate: { label: "Moderate", variant: "warning", bar: "border-l-amber-500" },
  low: { label: "Low", variant: "info", bar: "border-l-sky-500" },
  info: { label: "Information", variant: "neutral", bar: "border-l-slate-300 dark:border-l-slate-600" },
};

export function ReviewBadge({ review }: { review: ReviewState }) {
  if (review.state === "not_required") return null;
  if (review.state === "needs_review") return <Badge variant="warning">Needs review</Badge>;
  return <Badge variant={review.decision === "rejected" ? "neutral" : "success"}>{reviewLabel(review)} by clinician</Badge>;
}

export function Notice({ children, tone = "info", role }: { children: ReactNode; tone?: "info" | "warning" | "danger"; role?: "alert" | "status" }) {
  const tones = { info: "border-cyan-200 bg-cyan-50 text-cyan-900 dark:border-cyan-900 dark:bg-cyan-950/40 dark:text-cyan-100", warning: "border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-100", danger: "border-rose-200 bg-rose-50 text-rose-900 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-100" };
  return <div role={role} className={`flex items-start gap-3 rounded-lg border px-4 py-3 text-sm ${tones[tone]}`}><TriangleAlert className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" /><div className="min-w-0">{children}</div></div>;
}

function EvidenceList({ evidence }: { evidence: Evidence[] }) {
  if (!evidence.length) return <p className="text-sm text-slate-600 dark:text-slate-400">No source — this finding is about information that is absent.</p>;
  return <ul className="space-y-1">{evidence.map((e) => <li key={e.ref} className="text-sm"><span className="font-medium text-slate-900 dark:text-slate-100">{e.label}</span>{e.date && <span className="text-slate-500 dark:text-slate-400"> · {formatDate(e.date)}</span>}<span className="ml-2 font-mono text-xs text-slate-400">{e.ref}</span></li>)}</ul>;
}

// WHAT / WHY / SOURCE / WHAT IS MISSING / ACTION — required for every finding by the backend contract.
export function ExplanationBlock({ finding }: { finding: Finding }) {
  const e = finding.explanation;
  const row = (label: string, body: ReactNode) => <div className="grid gap-1 sm:grid-cols-[9rem_1fr]"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">{label}</dt><dd className="text-sm text-slate-800 dark:text-slate-200">{body}</dd></div>;
  return (
    <dl className="space-y-3">
      {row("What", e.what)}
      {row("Why", e.why)}
      {row("Source", <EvidenceList evidence={finding.evidence} />)}
      {row("What is missing", e.missing.length ? <ul className="list-disc space-y-0.5 pl-5">{e.missing.map((m) => <li key={m}>{m}</li>)}</ul> : "Nothing further identified.")}
      {row("Clinician action", e.action)}
      {finding.extra?.evidenceCoverage && row("Evidence coverage", `${finding.extra.evidenceCoverage.matched} of ${finding.extra.evidenceCoverage.recognised} recognised features (a count, not a probability)`)}
    </dl>
  );
}

export function FindingCard({ finding, defaultOpen = false }: { finding: Finding; defaultOpen?: boolean }) {
  const sev = SEVERITY[finding.severity];
  const isAi = finding.origin === "ai";
  const badge = finding.urgency
    ? <Badge variant={finding.urgency === "immediate_review" ? "critical" : "warning"}>{URGENCY_LABEL[finding.urgency]}</Badge>
    : <Badge variant={sev.variant}>{sev.label}</Badge>;
  return (
    <article data-testid={`finding-${finding.ruleId}`} className={`rounded-xl border-l-4 p-4 shadow-card ${sev.bar} ${provenanceFrame(isAi ? "ai" : "rules")}`}>
      <div className="flex flex-wrap items-center gap-2">
        <OriginTag origin={isAi ? "ai" : "rules"} />
        {badge}
        <ReviewBadge review={finding.review} />
        <span className="text-xs text-slate-500 dark:text-slate-400">{finding.category}</span>
      </div>
      <h3 className="mt-2 text-sm font-semibold text-slate-900 dark:text-slate-100">{finding.title}</h3>
      <p className="mt-1 text-sm text-slate-700 dark:text-slate-300">{finding.statement}</p>
      <details className="group mt-3" open={defaultOpen}>
        <summary className="cursor-pointer text-sm font-medium text-cyan-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-600 dark:text-cyan-300">Why this was raised · evidence</summary>
        <div className="mt-3 border-t border-slate-200 pt-3 dark:border-slate-800"><ExplanationBlock finding={finding} /></div>
      </details>
    </article>
  );
}

export function FindingList({ findings, empty }: { findings: Finding[]; empty: ReactNode }) {
  if (!findings.length) return <>{empty}</>;
  return <div className="space-y-3">{findings.map((f) => <FindingCard key={f.id} finding={f} />)}</div>;
}
